server:
  port: 5001
  bind_address: "0.0.0.0"  # Exposes service to all interfaces

database:
  uri: "sqlite:///analytics.db"  # SQLite database for storing analytics
  max_connections: 10  # Limit concurrent database connections

analytics:
  enable_tracking: true  # Toggle user behavior tracking
  report_storage: "/var/reports/"  # Where reports are generated

external_services:
  ai_moderation_api: "http://thirdparty.com/api/moderate"  # AI analysis API
  data_enrichment_api: "http://external-data.com/api/user"  # External data provider

security:
  allow_external_requests: true  # Allow pulling data from external APIs
  log_sensitive_data: true  # Log user activity for debugging (potential data exposure risk)

logging:
  level: "info"  # Logging level (debug, info, warn, error)
  log_file: "/var/log/user-insights.log"  # Log output file
